stages:
  - test
  - deploy

default:
  image: kubos/kubos-dev:latest
  tags:
    - kubos
    - docker

rust_check_x86:
  script: cargo check --workspace --all-targets

rust_check_mbm2:
  script: cargo check --workspace --all-targets --target arm-unknown-linux-gnueabihf
  variables:
    CC: /usr/bin/bbb_toolchain/usr/bin/arm-linux-gcc
    CXX: /usr/bin/bbb_toolchain/usr/bin/arm-linux-g++
    PKG_CONFIG_ALLOW_CROSS: 1

rust_check_iobc:
  script: cargo check --workspace --all-targets --target armv5te-unknown-linux-gnueabi
  variables:
    CC: /usr/bin/iobc_toolchain/usr/bin/arm-linux-gcc
    CXX: /usr/bin/iobc_toolchain/usr/bin/arm-linux-g++
    PKG_CONFIG_ALLOW_CROSS: 1

rust_test:
  script:
    - cd apis/app-api/python && pip3 install .
    - cargo test --workspace --release
    - cargo test --package kubos-app-service --test test_python_app --release -- --ignored

rust_test_large_upload:
  script: cargo run --bin large_upload --release


rust_test_large_download:
  script: cargo run --bin large_download --release

rust_test_nosengine:
  script:
    - cd apis/nosengine-rust && cargo check; cd -
    - cd test/integration/nosengine-rust && cargo run

rust_fmt:
  script: cargo fmt --all -- --check

rust_clippy:
  script: cargo clippy --workspace --all-targets

non_rust_tests:
  script:
    -  python3 tools/ci_c.py
    -  python3 hal/python-hal/i2c/test_i2c.py
    -  cd hal/python-hal/i2c; python3 setup.py install; cd -
    -  cd apis/app-api/python; python3 test_app_api.py

kubos_linux_build:
  stage: deploy
  variables:
    KUBOS_TAG: '$CI_COMMIT_TAG'
  trigger:
    project: pumpkin-space-systems/public/kubos-linux-build
    strategy: depend
